import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="main-container">
      <Head>
        <title>Bryce Cee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="place-content-center h-28">
        <article>
          <div className="font-bold">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi! Lorem ipsum dolor
            sit, amet consectetur adipisicing elit. Nemo culpa necessitatibus
            ipsa et inventore, amet temporibus molestias adipisci officia eius
            eos, deserunt quia quaerat facere laborum est provident, ad nisi!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi!
          </div>
          <div className="font-bold">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi! Lorem ipsum dolor
            sit, amet consectetur adipisicing elit. Nemo culpa necessitatibus
            ipsa et inventore, amet temporibus molestias adipisci officia eius
            eos, deserunt quia quaerat facere laborum est provident, ad nisi!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi!
          </div>
          <div className="font-bold">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi! Lorem ipsum dolor
            sit, amet consectetur adipisicing elit. Nemo culpa necessitatibus
            ipsa et inventore, amet temporibus molestias adipisci officia eius
            eos, deserunt quia quaerat facere laborum est provident, ad nisi!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi!
          </div>
          <div className="font-bold">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi! Lorem ipsum dolor
            sit, amet consectetur adipisicing elit. Nemo culpa necessitatibus
            ipsa et inventore, amet temporibus molestias adipisci officia eius
            eos, deserunt quia quaerat facere laborum est provident, ad nisi!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi!
          </div>
          <div className="font-bold">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi! Lorem ipsum dolor
            sit, amet consectetur adipisicing elit. Nemo culpa necessitatibus
            ipsa et inventore, amet temporibus molestias adipisci officia eius
            eos, deserunt quia quaerat facere laborum est provident, ad nisi!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi!
          </div>
          <div className="font-bold">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi! Lorem ipsum dolor
            sit, amet consectetur adipisicing elit. Nemo culpa necessitatibus
            ipsa et inventore, amet temporibus molestias adipisci officia eius
            eos, deserunt quia quaerat facere laborum est provident, ad nisi!
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo culpa
            necessitatibus ipsa et inventore, amet temporibus molestias adipisci
            officia eius eos, deserunt quia quaerat facere laborum est
            provident, ad nisi! Lorem ipsum dolor sit, amet consectetur
            adipisicing elit. Nemo culpa necessitatibus ipsa et inventore, amet
            temporibus molestias adipisci officia eius eos, deserunt quia
            quaerat facere laborum est provident, ad nisi!
          </div>
          
        </article>
      </main>

      <footer className="flex h-28 bg-cyan-600 items-center justify-center">
        Footer Section
      </footer>
    </div>
  );
}

export default Home
